//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Disruption) DeepCopyInto(out *Disruption) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Disruption.
func (in *Disruption) DeepCopy() *Disruption { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Limits) DeepCopyInto(out *Limits) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Limits.
func (in Limits) DeepCopy() Limits { _ = "STUB: not implemented"; return *new(Limits) }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NillableDuration) DeepCopyInto(out *NillableDuration) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NillableDuration.
func (in *NillableDuration) DeepCopy() *NillableDuration { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClaim) DeepCopyInto(out *NodeClaim) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClaim.
func (in *NodeClaim) DeepCopy() *NodeClaim { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeClaim) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClaimList) DeepCopyInto(out *NodeClaimList) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClaimList.
func (in *NodeClaimList) DeepCopy() *NodeClaimList { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeClaimList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClaimSpec) DeepCopyInto(out *NodeClaimSpec) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClaimSpec.
func (in *NodeClaimSpec) DeepCopy() *NodeClaimSpec { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClaimStatus) DeepCopyInto(out *NodeClaimStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClaimStatus.
func (in *NodeClaimStatus) DeepCopy() *NodeClaimStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClaimTemplate) DeepCopyInto(out *NodeClaimTemplate) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClaimTemplate.
func (in *NodeClaimTemplate) DeepCopy() *NodeClaimTemplate { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClaimTemplateSpec) DeepCopyInto(out *NodeClaimTemplateSpec) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClaimTemplateSpec.
func (in *NodeClaimTemplateSpec) DeepCopy() *NodeClaimTemplateSpec {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClassReference) DeepCopyInto(out *NodeClassReference) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClassReference.
	return
}

func (in *NodeClassReference) DeepCopy() *NodeClassReference { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePool) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolList) DeepCopyInto(out *NodePoolList) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolList.
func (in *NodePoolList) DeepCopy() *NodePoolList { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePoolList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolSpec) DeepCopyInto(out *NodePoolSpec) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolSpec.
func (in *NodePoolSpec) DeepCopy() *NodePoolSpec { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolStatus) DeepCopyInto(out *NodePoolStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolStatus.
func (in *NodePoolStatus) DeepCopy() *NodePoolStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorRequirementWithMinValues) DeepCopyInto(out *NodeSelectorRequirementWithMinValues) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorRequirementWithMinValues.
func (in *NodeSelectorRequirementWithMinValues) DeepCopy() *NodeSelectorRequirementWithMinValues {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectMeta) DeepCopyInto(out *ObjectMeta) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMeta.
func (in *ObjectMeta) DeepCopy() *ObjectMeta { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	_ = "STUB: not implemented"
	return nil
}
