/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package kwok

import (
	"context"
	_ "embed"
	"regexp"

	corev1 "k8s.io/api/core/v1"

	"sigs.k8s.io/karpenter/pkg/cloudprovider"
)

var (
	// AWS uses (family).(size) format
	awsRegexp = regexp.MustCompile(`^\w+\.(nano|micro|small|medium|large|\d*xlarge|metal)$`)

	familyDelim = regexp.MustCompile(`[.-]`)
)

// Wrap cloudprovider.Offerings with NodeSelectorRequirements for post-json processing translation
type KWOKOfferings []KWOKOffering

type KWOKOffering struct {
	cloudprovider.Offering
	Requirements []corev1.NodeSelectorRequirement
}

type InstanceTypeOptions struct {
	Name             string              `json:"name"`
	Offerings        KWOKOfferings       `json:"offerings"`
	Architecture     string              `json:"architecture"`
	OperatingSystems []corev1.OSName     `json:"operatingSystems"`
	Resources        corev1.ResourceList `json:"resources"`

	// These are used for setting default requirements, they should not be used
	// for setting arbitrary node labels.  Set the labels on the created NodePool for
	// that use case.
	instanceTypeLabels map[string]string
}

//go:embed instance_types.json
var defaultRawInstanceTypes []byte

// ConstructInstanceTypes create many instance types based on the embedded instance type data
func ConstructInstanceTypes(ctx context.Context) ([]*cloudprovider.InstanceType, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// parseSizeFromType will attempt to discover the instance size if it matches a special AWS format.
// If not, fall back to the cpu value.  This works for both Azure and GCP (and the "generic" instances
// generated by tools/gen_instances.go)
func parseSizeFromType(ty, cpu string) string { _ = "STUB: not implemented"; return "" }

// parseFamilyFromType will attempt to discover the instance family from the node type.  Some examples of
// well-known cloud provider formats:
//
// AWS   - [Family].[Size]
// GCP   - [Family]-[Configuration]-[# of vCPUs])
// Azure - [Family] + [Sub-family]* + [# of vCPUs] + ... + [Version]
//
// So here, we split on [.-], and if that fails, fall back to the first character of the instance type name.
func parseFamilyFromType(instanceType string) string { _ = "STUB: not implemented"; return "" }

func setDefaultOptions(opts InstanceTypeOptions) InstanceTypeOptions {
	_ = "STUB: not implemented"
	return *new(InstanceTypeOptions)
}

// if the user specified a different pod limit, override the default

// Default number of pods on a node in Kubernetes

// make sure all the instance types are available

func newInstanceType(options InstanceTypeOptions) *cloudprovider.InstanceType {
	_ = "STUB: not implemented"
	return nil
}
