//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package scheduling

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPort) DeepCopyInto(out *HostPort) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPort.
func (in *HostPort) DeepCopy() *HostPort { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPortUsage) DeepCopyInto(out *HostPortUsage) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPortUsage.
func (in *HostPortUsage) DeepCopy() *HostPortUsage { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Requirement) DeepCopyInto(out *Requirement) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Requirement.
func (in *Requirement) DeepCopy() *Requirement { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeUsage) DeepCopyInto(out *VolumeUsage) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeUsage.
func (in *VolumeUsage) DeepCopy() *VolumeUsage { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Volumes) DeepCopyInto(out *Volumes) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Volumes.
func (in Volumes) DeepCopy() Volumes { _ = "STUB: not implemented"; return *new(Volumes) }
